import { CDN_URL } from '../../configs';

export const data = [
  {
    id: 0,
    img: 'https://vbee.s3.ap-southeast-1.amazonaws.com/images/case-study/quang-cao-du-lich.jpg',
    titleVi: 'Quảng cáo khu du lịch',
    titleEn: 'Tourist area advertising',
    categoryEn: 'Product introduction and promotion',
    categoryVi: 'Giới thiệu, quảng bá sản phẩm',
    author: 'Mạnh Dũng',
    avatar: `${CDN_URL}/images/avatars/avatar-2.png`,
    langVi: 'Tiếng Việt',
    langEn: 'English',
    video:
      'https://vbee.s3.ap-southeast-1.amazonaws.com/videos/case-study/du-lich.mp4',
  },
  {
    id: 1,
    img: 'https://vbee.s3.ap-southeast-1.amazonaws.com/images/case-study/quang-cao-oto.jpg',
    titleVi: 'Quảng cáo ô tô',
    titleEn: 'Car advertising',
    categoryEn: 'Product introduction and promotion',
    categoryVi: 'Giới thiệu, quảng bá sản phẩm',
    author: 'Thảo Trinh',
    avatar: `${CDN_URL}/images/avatars/avatar-2.png`,
    langVi: 'Tiếng Việt',
    langEn: 'English',
    video:
      'https://vbee.s3.ap-southeast-1.amazonaws.com/videos/case-study/review-oto.mp4',
  },
  {
    id: 2,
    img: 'https://vbee.s3.ap-southeast-1.amazonaws.com/images/case-study/review-giay.jpg',
    titleVi: 'Review giày',
    titleEn: 'Shoes review',
    categoryEn: 'Product introduction and promotion',
    categoryVi: 'Giới thiệu, quảng bá sản phẩm',
    author: 'Mạnh Dũng',
    avatar: `${CDN_URL}/images/avatars/avatar-1.png`,
    langVi: 'Tiếng Việt',
    langEn: 'English',
    video:
      'https://vbee.s3.ap-southeast-1.amazonaws.com/videos/case-study/review-giay.mp4',
  },
  {
    id: 3,
    img: 'https://vbee.s3.ap-southeast-1.amazonaws.com/images/case-study/review-phim.jpg',
    titleVi: 'Review phim Squid Game',
    titleEn: 'Squid Game Movie review',
    categoryEn: 'Instruction and Review',
    categoryVi: 'Hướng dẫn, review',
    author: 'Ngọc Huyền',
    avatar: `${CDN_URL}/images/avatars/avatar-2.png`,
    langVi: 'Tiếng Việt',
    langEn: 'English',
    video:
      'https://vbee.s3.ap-southeast-1.amazonaws.com/videos/case-study/review-phim.mp4',
  },
  {
    id: 4,
    img: 'https://vbee.s3.ap-southeast-1.amazonaws.com/images/case-study/hdsd-test-nhanh-covid.jpg',
    titleVi: 'Hướng dẫn sử dụng bộ test nhanh',
    titleEn: 'User manual testing Covid tutorial',
    categoryEn: 'Instruction and Review',
    categoryVi: 'Hướng dẫn, review',
    author: 'Minh Hoàng',
    avatar: `${CDN_URL}/images/avatars/avatar-1.png`,
    langVi: 'Tiếng Việt',
    langEn: 'English',
    video:
      'https://vbee.s3.ap-southeast-1.amazonaws.com/videos/case-study/test-nhanh-covid.mp4',
  },
  {
    id: 5,
    img: 'https://vbee.s3.ap-southeast-1.amazonaws.com/images/case-study/review-sach.jpg',
    titleVi: 'Review sách',
    titleEn: 'Book review',
    categoryEn: 'Instruction and Review',
    categoryVi: 'Hướng dẫn, review',
    author: 'Thảo Trinh',
    avatar: `${CDN_URL}/images/avatars/avatar-2.png`,
    langVi: 'Tiếng Việt',
    langEn: 'English',
    video:
      'https://vbee.s3.ap-southeast-1.amazonaws.com/videos/case-study/review-sach.mp4',
  },
  {
    id: 6,
    img: 'https://vbee.s3.ap-southeast-1.amazonaws.com/images/case-study/bai-giang-tu-dong.jpg',
    titleVi: 'Bài giảng đại học trực tuyến',
    titleEn: 'Online college lectures',
    categoryEn: 'Lecture',
    categoryVi: 'Bài giảng, thuyết trình',
    author: 'Mai Phương',
    avatar: `${CDN_URL}/images/avatars/avatar-4.png`,
    langVi: 'Tiếng Việt',
    langEn: 'English',
    video:
      'https://vbee.s3.ap-southeast-1.amazonaws.com/videos/case-study/bai-giang.mp4',
  },
  {
    id: 7,
    img: 'https://vbee.s3.ap-southeast-1.amazonaws.com/images/case-study/thuyet-trinh-o-nhiem.jpg',
    titleVi: 'Ô nhiễm môi trường',
    titleEn: 'Environment pollution',
    categoryEn: 'Lecture',
    categoryVi: 'Bài giảng, thuyết trình',
    author: 'Minh Hoàng',
    avatar: `${CDN_URL}/images/avatars/avatar-3.png`,
    langVi: 'Tiếng Việt',
    langEn: 'English',
    video:
      'https://vbee.s3.ap-southeast-1.amazonaws.com/videos/case-study/o-nhiem-nuoc.mp4',
  },
  {
    id: 8,
    img: 'https://vbee.s3.ap-southeast-1.amazonaws.com/images/case-study/thuyet-trinh-lich-su.jpg',
    titleVi: 'Thuyết trình lịch sử Việt Nam',
    titleEn: 'Vietnamese history presentation',
    categoryEn: 'Lecture',
    categoryVi: 'Bài giảng, thuyết trình',
    author: 'Hương Giang',
    avatar: `${CDN_URL}/images/avatars/avatar-5.png`,
    langVi: 'Tiếng Việt',
    langEn: 'English',
    video:
      'https://vbee.s3.ap-southeast-1.amazonaws.com/videos/case-study/lich-su.mp4',
  },
];
