export const BRAND_NAME = 'Vbee AI Voice Studio';
export const TEXT_MAX_LENGTH = 500;
export const VBEE = 'Vbee - Text To Speech';
export const VBEE_AI_CLIP = 'Vbee AI Clip';
export const VBEE_AI_CALL_CENTER = 'Vbee AI Call Center';
export const VBEE_SMART_DIALOG = 'Vbee SmartDialog';
export const VBEE_BLOG = 'Vbee Blog';
export const VBEE_EMAIL = 'contact@vbee.vn';
export const VBEE_SUPPORT_PHONE_NUMBER = '024.9999.3399';
export const VBEE_HOTLINE_PHONE_NUMBER = '0901 533 799';
export const VBEE_LICENSE = 'Copyright 2021 Vbee JSC. All rights reserved';
export const VBEE_STUDIO = 'Vbee Studio';
export const VBEE_API = 'Vbee API';
export const VND = 'VNĐ';
export const WEBSITE = 'Vbee.vn';
export const VBEE_EMAIL_SUPPORT = 'support@vbee.vn';
export const TTS_WEBSOCKET_URL = `${process.env.TTS_WEBSOCKET_URL}/api/v1/synthesis`;
export const MAX_WIDTH = '2xl:w-1440';
export const VBEE_FACEBOOK_URL = 'https://www.facebook.com/groups/congdongvbee';
export const VBEE_BLOG_URL = 'https://blogs.vbee.vn';
export const VBEE_AI_CLIP_URL = 'https://aiclip.ai';
export const VBEE_AI_AICC_URL = 'https://aicallcenter.vn';
export const VBEE_SMART_DIALOG_URL = 'https://smartdialog.vn';
export const VBEE_PRIVACY_POLICY_URL = 'https://vbee.vn/chinh-sach-bao-mat';
export const VBEE_TERM_OF_USE_URL =
  'https://vbee.vn/chinh-sach-va-quy-dinh-chung';
export const VBEE_FACEBOOK_SOCIAL_URL =
  'https://www.facebook.com/vbee.aivoicesolutions';
export const VBEE_ZALO_URL = 'https://zalo.vbee.vn';
export const VBEE_GOOGLE_URL = 'contact@vbee.vn';
export const VBEE_YOUTUBE_URL = 'https://www.youtube.com/c/VbeeGroup';
export const VBEE_TIKTOK_URL = 'https://www.tiktok.com/@vbee.official';
export const VBEE_MESSENGER_URL = 'https://www.messenger.com/t/738986426449704';
export const CRM_REDIRECT_URI = `${process.env.CRM_URL}/studio/text-to-speech`;
export const CRM_PAYMENT_REDIRECT_URI = `${process.env.CRM_URL}/studio/payments`;
export const { API_URL } = process.env;
export const { CRM_URL } = process.env;
export const { GTM_ID } = process.env;
export const { NODE_ENV } = process.env;
export const CDN_URL = NODE_ENV === 'production' ? process.env.CDN_URL : '';
export const OLD_VERSION_VBEE_URL = 'https://v3.vbee.vn';
export const VBEE_USER_GUIDE_URL = 'https://help.vbee.vn/docs/user-guide/';
export const VBEE_DOMAIN_URL = 'https://help.vbee.vn/docs/case-study/';
export const VBEE_DEVELOPER_URL = 'https://help.vbee.vn/docs/developer/';
export const VBEE_DOCUMENT_URL = 'https://help.vbee.vn/docs/resources/';
export const VBEE_ANDROID_APP_URL =
  'https://play.google.com/store/apps/details?id=vn.vbee.tts';
export const VBEE_IOS_APP_URL =
  'https://apps.apple.com/vn/app/vbee-text-to-speech/id1598093001?l=vi';
