/* eslint-disable react/no-danger */
/* eslint-disable @next/next/next-script-for-ga */
import Head from 'next/head';
import HeaderLayout from './headerLayout';
import Footer from './footer';
import { GTM_ID, VBEE } from '../../configs';
import CustomerCare from './custormerCare';
import ScrollToTopButton from './scrollToTopButton';

const Layout = ({ children }) => (
  <div>
    <Head>
      <title>{VBEE} </title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.png" />

      <script
        dangerouslySetInnerHTML={{
          __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
          new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
          j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
          'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
          })(window,document,'script','dataLayer', ${GTM_ID});`,
        }}
      />
    </Head>
    <main>
      <noscript
        dangerouslySetInnerHTML={{
          __html: `<iframe src="https://www.googletagmanager.com/ns.html?id=${GTM_ID}"
          height="0" width="0" style="display:none;visibility:hidden"></iframe>`,
        }}
      />
      <div className="relative">
        <HeaderLayout />
        {children}
        <div className="flex justify-center">
          <Footer />
        </div>
        <div className="fixed bottom-4 right-4">
          <ScrollToTopButton />
        </div>
        <div className="fixed bottom-4 left-4">
          <CustomerCare />
        </div>
      </div>
    </main>
  </div>
);

export default Layout;
